{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel.secretName" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  APP_NAME: {{ .Values.app.name | quote }}
  APP_ENV: {{ .Values.app.env | quote }}
  APP_DEBUG: {{ .Values.app.debug | quote }}
  APP_URL: {{ .Values.app.url | quote }}
  APP_KEY: {{ .Values.app.key | quote }}
  DB_CONNECTION: {{ .Values.app.dbConnection | quote }}
  DB_HOST: {{ .Values.app.dbHost | quote }}
  DB_PORT: {{ .Values.app.dbPort | quote }}
  DB_DATABASE: {{ .Values.app.dbName | quote }}
  DB_USERNAME: {{ .Values.app.dbUser | quote }}
  DB_PASSWORD: {{ .Values.app.dbPassword | quote }}
  {{- if .Values.app.mysqlAttrSslCa }}
  MYSQL_ATTR_SSL_CA: {{ .Values.app.mysqlAttrSslCa | quote }}
  {{- end }}
  {{- with .Values.app.extraEnv }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.secret.stringData }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
